### ISSUE TITLE
Uses oldest version of a mod

### ISSUE THREAD

**Issue by gsitcia** [froehlichA/pax#10]
This is on the latest commit.

On [line 73 in cmdutils.nim](https://github.com/froehlichA/pax/blob/20b5896f5fb8c6dc805c706ee758b2135de1b328/src/cmd/cmdutils.nim#L73) the > should be a <

**Comment by froehlichA** [comment]
Oh thanks, that's probably the culprit of #9 :D
I'll be fixing that later today.

In the meantime, you can use the latest version of the binary [here](https://github.com/froehlichA/pax/releases/tag/v0.8-beta) which doesn't include the "checking for forge/fabric compability" feature and therefore doesn't have this bug.
