### ISSUE TITLE
Use CurseForge Fabric support instead of Jumploader

### ISSUE THREAD

**Issue by MarioAndWeegee3** [froehlichA/pax#21]
CurseForge added native Fabric support recently, so Jumploader is no longer needed for CurseForge packs.

Proposed changes:
- `--loader fabric` uses a Fabric instance rather than Jumploader
- Possibly an option to upgrade existing packs using Jumploader to native Fabric

**Comment by froehlichA** [comment]
Sure! I'll get on that right away.

**Comment by froehlichA** [comment]
Fixed! Grab the v1.2.0 release.

To create a new fabric modpack:
- `./pax init` (no change)

To migrate from existing packs:
- `./pax remove jumploader`
- `./pax version <mc-version> --loader fabric`
