### ISSUE TITLE
Cannot add mods in latest version.

### ISSUE THREAD

**Issue by baltassarmonkey** [froehlichA/pax#32]
Used pax to create a simple test modpack a few days ago, have since updated the version of pax (from version 1.2.1 to 1.4.0 or 1.3.0) and I can no longer add mods to any modpack.

Tried redownloading the latest versions, and making new modpacks to no avail (forge, fabric, 1.16.5, 1.17...)

This is the response I get when trying to add a mod with the new versions:

`$ ./pax add lithium`
`[:] Loading data from manifest..`
`[:] Searching for mod..`
`httpclient.nim(1080)     responseContentIter`
`asyncfutures.nim(390)    read`
`asyncfutures.nim(390)    read`
`asyncfutures.nim(390)    read`
`asyncfutures.nim(390)    read`
`Error: unhandled exception: 400 Bad Request [HttpRequestError]`

When I roll back to the 1.2.1 release the command works as expected.

**Comment by froehlichA** [comment]
Ok, got the error.

- In the old versions, I was retrieving 50 mods at once from the Forge API.
- In the new version, I'm retrieving 100 mods at once from the Forge API,
  - Apparently this used to work a few days ago when testing but doesn't work anymore? Somehow?

Doesn't matter, I can just reset it to 50 again and it should work. Bugfix coming in a few minutes.

**Comment by froehlichA** [comment]
Fixed in latest release.
