### ISSUE TITLE
Allow pax executable to be placed in a different folder.

### ISSUE THREAD

**Issue by baltassarmonkey** [froehlichA/pax#33]
Currently the pax executable along with extra libraries for windows, needs to be placed in the same directory as the modpack. However it would be nice if I could place it elsewhere, add it to the PATH, and simply use it in any folder I wish. This would be especially helpful when working on different modpacks at the same time (avoids the need for multiple installations).

If I try running the pax executable from a different folder it just hangs at the moment.

**Comment by MrAwesomeRocks** [comment]
I have it in `C:\pax` with the folder added to my path and it works fine. Are you doing `./pax` or just `pax`?

**Comment by baltassarmonkey** [comment]
Using `pax` since `./pax` looks for the executable in the current directory and therefore doesn't find anything.
I have a folder with the pax executable inside added to path, windows can find it since it doesn't throw an error when I try to run any pax command, however the program seems to not give any response.

pax seems to hang, not producing any output until I use Ctrl+C to kill it:
`$ pax init`

`Signal caught, cleaning up.`

**Comment by froehlichA** [comment]
I've tested it on my system - It works for me regardless of my pax binary location.

One possible issue could be that it's just a naming conflict. Try executing the following command in the Windows command line:
```
where pax.exe
```

This should list you all possible locations of an executable called `pax.exe` in your path. If you have any other binaries called `pax` in your path, it is most likely a naming conflict - Simply rename `pax.exe` to `paxmc.exe` or another name then.

**Comment by baltassarmonkey** [comment]
Many thanks, this was indeed the issue. Turns out pax is an executable from git bash for windows.
