### ISSUE TITLE
index out of bounds

### ISSUE THREAD

**Issue by yo56789** [froehlichA/pax#47]
When doing: ``pax add https://www.curseforge.com/minecraft/mc-mods/dtbop`` i get an error which is 
fatal.nim(49)            sysFatal 
asyncfutures.nim(390)    read
Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]

When i try and add any other mod i do not get this error. This is happening for Version 1.7.1
I am also getting the exact same error when doing: ``pax add https://www.curseforge.com/minecraft/mc-mods/dtphc``

I am only getting this error when adding the mod with the url. If i install it the normal way without the url i do not get this error

**Comment by froehlichA** [comment]
When you add mods with a curseforge link, a search is started the project id (in your case `dtbop`) which might not find the desired mod. 
---
I'll look into the issue as soon as possible.

**Comment by froehlichA** [comment]
Fixed in latest release: https://github.com/froehlichA/pax/releases/tag/v1.7.2
