### ISSUE TITLE
Sync with MultiMC

### ISSUE THREAD

**Issue by juraj-hrivnak** [froehlichA/pax#49]
```
MultiMC/
└── instances/
    └── yourcreatedfolder/
        └── minecraft/
            └── mods/
```

**Comment by froehlichA** [comment]
If you're talking about syncing mod/config changes between the pax project and a Minecraft instance, I already have an issue open for that (https://github.com/froehlichA/pax/issues/28).

Otherwise please clarify further ;)

**Comment by juraj-hrivnak** [comment]
Sorry for the late reply. 
Yes, I did mean the syncing mod/config changes between the pax project and a Minecraft instance.

**Comment by froehlichA** [comment]
Ok, no problem ^^
I'm going to close this issue, you can track progress done on the #28 issue.
