### ISSUE TITLE
Can't use custom .out folder or export name, or change pack versions

### ISSUE THREAD

**Issue by Beethoven-n** [froehlichA/pax#50]
i'd love to be able to do `pax export ./builds/Fabric-Skies-1.4.0.zip` to export to a custom location and a custom file. 
also an argument to set a pack version, rather than just MC or loader versions

**Comment by froehlichA** [comment]
> i'd love to be able to do pax export ./builds/Fabric-Skies-1.4.0.zip to export to a custom location and a custom file.
No worries, I'll implement that.

> also an argument to set the pack version
I'm not sure a command is needed for this: You can change the `version` manually in the `manifest.json`.
The `./pax version` command only exists because the loader version needs to be updated when switching between minecraft versions.

**Comment by Beethoven-n** [comment]
ahh, it'd just be nice to have a version appended to every export on top of the name since i keep track of pack versions too

**Comment by froehlichA** [comment]
You can now export to a custom path in the latest release, like this: `./pax export ./builds/Fabric-Skies-1.4.0.zip`.

---

If you want to automatically get the output zip name based on your current modpack version, you can use:
```bash
./pax export "./builds/Fabric-Skies-$(cat modpack/manifest.json | jq -r '.version').zip"
```
(Assuming you're running this either on Linux or on a CI.)

**Comment by Beethoven-n** [comment]
> You can now export to a custom path in the latest release, like this: `./pax export ./builds/Fabric-Skies-1.4.0.zip`.
> 
> If you want to automatically get the output zip name based on your current modpack version, you can use:
> 
> ```shell
> ./pax export "./builds/Fabric-Skies-$(cat modpack/manifest.json | jq -r '.version').zip"
> ```
> 
> (Assuming you're running this either on Linux or on a CI.)

just so you know, you don't have to cat into `jq`, `jq` already gets the contents of that file
`jq -r '.version'` is good enough in that. probably gonna just put this in my shell rc, pardon space indentation
```shell
paxex() {
  pax export "builds/`jq -r '.name'`-`jq -r '.version'`.zip"
}
```
