### ISSUE TITLE
Support for curseforge resource packs

### ISSUE THREAD

**Issue by juraj-hrivnak** [froehlichA/pax#53]
To be able to release modpack on the CurseForge, resource pack files should be referenced in the `manifest.json`. 
Otherwise, the modpack will be rejected.

**Comment by froehlichA** [comment]
Good idea! For now, you can add them manually to the manifest, but I'll add the feature later.

**Comment by froehlichA** [comment]
Marked as bug, because adding a resourcepack manually breaks pax.

**Comment by froehlichA** [comment]
Ok, after testing again I realised pax *doesn't* break anymore with a resource pack, at least not when I'm testing.
If it does for you, try updating to the newest version first, if that still doesn't help, tell me about what commands are causing a crash for you.

The act of adding a resource pack with `./pax add` would complicate things a bit, I'm gonna think about how to manage them a bit longer.
`./pax upgrade` should also work with resource packs.

**Comment by juraj-hrivnak** [comment]
I was exporting my modpack with the resource pack in the manifest with no problem, even on the older version of Pax. But, thanks for the info!

Running `./pax add` also for resource pack could be confusing. Hard to tell how to make it. Take your time with it!
Oh, that's great.
