### ISSUE TITLE
Cannot define Forge Version

### ISSUE THREAD

**Issue by RevLaw** [froehlichA/pax#61]
Pax is using an old Forge Version. 

Minecraft version is set via: `pax version 1.16.5`

I get the following issue up on starting minecraft:
`net.minecraftforge.fml.ModLoadingException: Mod §eindustrialforegoing§r requires §6forge§r §o36.2.8 or above§r
§7Currently, §6forge§r§7 is §o36.2.0`

**Comment by froehlichA** [comment]
If available, pax uses the recommended version of forge, which is currently `36.2.0` for `1.16.5`.
I think I'm going to add a `--latest` flag to `./pax version` so you can select the latest version automatically.

In the meantime, you can manually change your forge version by opening `modpack/manifest.json` and replacing
```
"id": "forge-36.2.0"
```
with 
```
"id": "forge-36.2.9"
```

**Comment by froehlichA** [comment]
You're now able to use `./pax version <version> --latest` to switch to the latest loader version.
