### ISSUE TITLE
Issue | web request errors

### ISSUE THREAD

**Issue by GalGreenfield** [froehlichA/pax#68]
I'm trying to `pax import` my modpack package and after some time of it runing I'm getting the following error:
```httpclient.nim(308)      httpError
asyncfutures.nim(372)    read
asyncfutures.nim(372)    read
asyncfutures.nim(372)    read
asyncfutures.nim(372)    read
asyncfutures.nim(372)    read
asyncfutures.nim(372)    read
asyncfutures.nim(372)    read
???                      fetchAddonIter
asyncfutures.nim(372)    read
asyncfutures.nim(372)    read
Error: unhandled exception: Connection was closed before full request has been made [ProtocolError]
```

Can you please help me fix them?

**Comment by froehlichA** [comment]
This is an issue with Pax using the new CF proxy, which has rate limiting.
While I fix this issue, you can use the previous pax version (v1.9.7) :D

(also duplicates #67, so I'll close this one & I'll write a comment into #67 once this is fixed)
