### ISSUE TITLE
export 95 mods only creates 4kb file

### ISSUE THREAD

**Issue by Hyjinksia** [froehlichA/pax#73]
I have added 95 mods to a new init creation.  When I export I only get 4kb and no mods.

**Comment by froehlichA** [comment]
Pax doesn't download the mod .jar files. Pax creates a modpack format like the one used by https://www.curseforge.com/. You can import a pax modpack using launchers like [GDLauncher](https://gdevs.io/) or [PolyMC](https://polymc.org/).
