### ISSUE TITLE
`pax upgrade` hangs on Windows due to improper cache path

### ISSUE THREAD

**Issue by MrAwesomeRocks** [froehlichA/pax#74]
On Windows, `:` cannot be used in a filename, however, the cache files are named `file:ADDON`, leading to the cache directory simply containing two empty files with names `file` and `addon` and causing long upgrade times.

This can be fixed by simply using a different separator.

**Comment by froehlichA** [comment]
Thanks for the quick PR ^^
I'll have to fix some of the tests first, but I hope that i can have a new Pax version out by wednesday. In the meantime, you can try using a version of Pax without the cache (https://github.com/froehlichA/pax/releases/tag/v1.9.9).
