### ISSUE TITLE
Is there support for MacOS?

### ISSUE THREAD

**Issue by TheRealWulf** [froehlichA/pax#79]
I am trying to get it to work on my Mac but I must be doing it wrong or there's no support. I checked the wiki for help on this, but nothing is there for my issue.

**Comment by froehlichA** [comment]
Pax is not officially supported on Mac because I don't have one I can test it on. Someone in my Discord built it on their macOS M1 though, you can either message them about how they did it or try [building it yourself](https://github.com/froehlichA/pax#pax-development).

**Comment by TheRealWulf** [comment]
Thank you, I will look into it!
