### ISSUE TITLE
fetch dependencies when installing & updating mods

### ISSUE THREAD

**Issue by froehlichA** [froehlichA/pax#8]
the api actually returns dependencies as well, so we gotta use that.

**Comment by DAmNRelentless** [comment]
This would also be nice when uninstalling mods.
There is no launcher which can do this yet.

If you uninstall a mod, pax could check if there are remaining mods using the same dependencies. If yes, leave them be, if not uninstall them as well. Maybe with some info output or as a flag you can use like `uninstall -d <mod`. And when you provide the `-d` flag, the dependencies will be checked as well.

Pretty insane would be deleting configs from uninstalled mods but that would require reading the mod's JAR file to get their mod id or custom configs.
